version: build{build}

image: Visual Studio 2015

environment:
  access_token:
    secure: DXAumCpZjJ3erz0OmBJybIJTwux9uSrdtqKtezd4wI9b2ELz3NELPwZfp+WfYKtb
  matrix:
    - QT_PATH : C:\Qt\5.11.2\msvc2015_64\bin
      PLATFORM : amd64
      OUTPUT_BIN_DIR : bin64
    - QT_PATH : C:\Qt\5.11.2\msvc2015\bin
      PLATFORM : x86
      OUTPUT_BIN_DIR : bin32

clone_folder: c:\dev\labrador
clone_depth: 1
configuration: Release

branches:
  only:
    - master

init:
  - set PATH=%QT_PATH%;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%

before_build:
  - cd c:\dev\labrador\Desktop_Interface 

build_script:
  - qmake
  - nmake

after_build:
  - windeployqt bin\Labrador.exe
  - del bin\vcredist*.exe
  - del bin\*.pdb

artifacts:
  - path: Desktop_Interface\bin
    name: Labrador_%PLATFORM%
    type: zip
    

    
matrix:
  fast_finish: true
